.TH DIARY 1
.SH NAME
diary \- Simple text-based diary program

.SH SYNOPSIS
.B diary
[\fIOPTION\fR]... [\fIDIRECTORY\fR]...
.br

.SH DESCRIPTION
.B diary
is a simple text-based program for managing journal entries.

.SH ENVIRONMENT

.IP DIARY_DIR
If this variable is set to a directory that can be opened,
.B diary
will use it to store diary files. Diary files are simple text files named
after their date, formatted like YYYY-MM-DD. All other files are ignored.

.IP EDITOR
The program used to edit journal entries.


.SH ARGUMENTS

If the argument \fIDIRECTORY\fR is given, diary files are read from and
stored to that directory, ignoring the DIARY_DIR environment variable or
any '-d' or '--dir' options.

.SH NAVIGATION
Navigation is done using the following vim-inspired keyboard shortcuts:

.TS
tab(|);
l l.
Key(s)    | Action
======    | ======
k, up     | go backward by 1 week
j, down   | go forward by 1 week
h, left   | go backward by 1 day
l, right  | go forward by 1 day
J         | go forward by 1 month
K         | go backward by 1 month

e, enter  | edit current entry
d, x      | delete current entry
q         | quit the program

N         | go to the previous journal entry
n         | go to the next journal entry
g         | go to the first journal entry
G         | go to the last journal entry

t         | jump to today
s         | jump to specific day
.TE


.SH DEVELOPMENT
All source code is available in this github repository:
<https://github.com/in0rdr/diary/>. Contributions are always welcome!
