#!/bin/bash
# backups/update_all

test -d backups || mkdir backups

for f in `find . -maxdepth 1 -type f`; do
	[ './update_all' = $f ] && continue 
	[ './.gitignore' = $f ] && continue 
	real_loc=`head -n 2 $f | tail -n 1 | awk '{print $2}'`

	#I strongly suspect that this is not a portable script because of this next line. That line also forces it to be a bash script. Oh well
	real_loc="${real_loc/#~/$HOME}"
	test -f $real_loc || $(echo Could not find file $real_loc && continue)

	echo "cp $f $real_loc"
	cp $real_loc backups/
	cp $f $real_loc
done
