#!/bin/bash

for arg in "$@"; do

name=$arg
# lowercase only
name=${name,,}
# spaces to underscores
name=${name// /_}
# hyphen to underscores
name=${name//-/_}
# remove quotes
name=${name//\'/}

# hack to remove all runs of underscores
for i in {1..5}; do
	name=${name//__/_}
done

[ "$arg" == "$name" ] || echo $name && mv "$arg" $name

done
