#!/bin/sh

action=$(echo "Install Program\nRemove Program\nUpdate Programs\nAutoremove\nRemove Dependency\nClear Pacman Cache\nRemove System Journal" | dmenu -i -p "Tradwife Pacman")

# Not sure how I can use this with doas instead of sudo

case $action in
"Install Program")
	program_to_install=$(pacman -Si | awk '/^Name/{name=$3} /^Installed Size/{is=$4$5} /^Description/{sub(/^.{18}/,"",$0);{desc=$0};printf("%-18s [%-9s] -> %s\n", name, is, desc)}' | dmenu -i -l 25 | awk '{print $1}')
	if [ ! -z "$program_to_install" ]; then
		sudo -A pacman -S --noconfirm "$program_to_install" > "$XDG_TRASH_HOME/misc/install.log"
		dunstify "Tradwife Pacman" "Hark! $program_to_install arrives anon!"
	fi
	;;
"Remove Program")
	program_to_remove=$(pacman -Qei | awk '/^Name/{name=$3} /^Installed Size/{is=$4$5} /^Description/{sub(/^.{18}/,"",$0);{desc=$0};printf("%-18s [%-9s] -> %s\n", name, is, desc)}' | dmenu -i -l 25 | awk '{print $1}')
	if [ ! -z "$program_to_remove" ]; then
		sudo -A pacman -R --noconfirm "$program_to_remove" > "$XDG_TRASH_HOME/misc/remove.log"
		dunstify "Tradwife Pacman" "Let us mourn $program_to_remove, slain in his youth"
	fi
	;;
"Remove Dependency")
	program_to_remove=$(pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{is=$4$5} /^Description/{sub(/^.{18}/,"",$0);{desc=$0};printf("%-18s [%-9s] -> %s\n", name, is, desc)}' | dmenu -i -l 25 | awk '{print $1}')
	if [ ! -z "$program_to_remove" ]; then
		sudo -A pacman -R --noconfirm "$program_to_remove" > "$XDG_TRASH_HOME/misc/remove.log"
		dunstify "Tradwife Pacman" "Friendship ended with $program_to_remove"
	fi
	;;
"Update Programs")
	sudo -A pacman -Syu --noconfirm > "$XDG_TRASH_HOME/misc/update.log" || dunstify --urgency=critical "Tradwife Pacman" "My mind... unravels"
	dunstify "Tradwife Pacman" "A new era of Knowledge"
	;;
"Autoremove")
	sudo -A pacman --noconfirm -Rs $(pacman -Qqtd) > "$XDG_TRASH_HOME/misc/remove.log"
	dunstify "Tradwife Pacman" "Cruft Eviscerated"
	;;
"Clear Pacman Cache")
	sudo -A pacman -Scc --noconfirm
	dunstify "Tradwife Pacman" "Removed da Cache, boss"
	;;
"Remove System Journal")
	sudo -A journalctl --vacuum-size=1M
	dunstify "Tradwife Pacman" "The archives must be incomplete"
	;;
*)
	dunstify "Tradwife Pacman" "Unknown option"
	;;
esac
