#!/bin/bash

command rm -f $XDG_TRASH_HOME/misc/mtime

for x in {1..25}; do
  /usr/bin/time -f "real %e user %U sys %S" -a -o $XDG_TRASH_HOME/misc/mtime $@ > /dev/null
  tail -1 $XDG_TRASH_HOME/misc/mtime
done

awk '{ et += $2; ut += $4; st += $6; count++ } END {  printf "Average:\nreal %.3f user %.3f sys %.3f\n", et/count, ut/count, st/count }' $XDG_TRASH_HOME/misc/mtime
